### ISSUE TITLE
Changing the license should be a major version change

### ISSUE THREAD

**Issue by Everspace** [faye/websocket-extensions-node#4]
License changes are a "breaking change" as far as the usability of packages is concerned for many organizations. The change should be reverted and published to a new version.

**Comment by jcoglan** [comment]
Hi @Everspace, is your organisation facing a problem because of this specific license change?

**Comment by Everspace** [comment]
No, but it has caused me grief in the past with legal.

**Comment by jcoglan** [comment]
To explain my reasoning here, I made a trade-off between making sure patches get to end users as smoothly as possible (considering there's no change in functionality) and publishing my work under terms I'm comfortable with.

In this particular case, I believe that anyone who was abiding by the license of prior releases will more-than-likely be in compliance with the license of the latest release. The restrictions added by Apache 2.0 compared to MIT mostly concern protection of myself from litigation, and conditions on distribution of modified copies of the work, which is a moot point for a brand new release where no such copies exist.

There are other changes of license that would have prompted me to release a new major version, but in this case I don't think it is warranted. In any case, I cannot revert releases that have already been published.

The way I understand it, licensing is orthogonal to versioning in that a license applies to a specific concrete text -- a single release or package, not to an abstract concept like a series of releases or the project as a whole. As such it must be possible for the author to assert their chosen terms over each published work, and users must continually ensure they're in compliance with licenses of releases they're using.

**Comment by Lewiscowles1986** [comment]
I wanted to come to say it's sketchy releasing a security fix with a license change.

I see that is not quite this issue, but they are so similar I didn't want to make a separate issue.

It is not that I doubt I would remain compliant, but more that it's a strong coupling of unrelated things from an engineering perspective. Releases are not dissimilar to pull-requests in that a diligent operator will at least glance at code changes, test, perhaps deploy before accepting.

To be honest I wouldn't care if it were major, minor or patch. I Just feel like the security fix should have been released separately to the license fix.

I'm fairly certain your understanding of licensing is too dictatorial as well. As a new user I have the choice to not use a thing or use it, this is on me.

This happens to have come bundled with Ruby on Rails as a dependency, so I actually didn't choose to use it, but if I did then we would have an explicit, existing agreement.

Past that point, once people have something using this in production, it would be rather hostile to suggest multiple people, possibly serving an amplified number of people are given this choice as well as others to accept your terms or stop using this.

When bundled with, or supporting other software that clear picture becomes blurred.

Of course it is your work so you can choose to behave as you like, think as you like, but the below quote seems to fall under the terms of what I would consider to be an unreasonable contract,

> it must be possible for the author to assert their chosen terms over each published work, and users must continually ensure they're in compliance with licenses of releases they're using.

Given 1000 node modules, which is not an uncommon number for serious software using nodejs the desire to have me care about each unique developers hot-takes on everything seems a bit much.

**Comment by jcoglan** [comment]
I would like to keep this issue focussed on whether anyone is having a specific problem adopting the latest release as a result of the license changing. If this is causing a concrete problem for end users then let's talk about that and not get side-tracked by arguing about the license _per se_.

**Comment by Lewiscowles1986** [comment]
Sorry, as I read it this was not about the license at all, but rather the release process.

**Comment by jcoglan** [comment]
We can't change releases that have already been published, so let's rather focus on whether those releases are creating a problem for users as they stand, and if so what we can do about it.

**Comment by JB1959** [comment]
Change license version change #4

**Comment by jcoglan** [comment]
@JB1959 this comment and the PR you just opened have the appearance of automated activity and I will block this account if this activity continues.

**Comment by eyn** [comment]
@jcoglan - I really appreciate your work on the module and its of course up to you how you license it however I found it a bit of a surprise to see a license change along with a security release. As I was reviewing our security patches I spotted this commit. I've got no problem with the Apache 2 license but I think its unexpected to see a license change in a minor point release and particularly tied into a security patch and it raises alarm bells that a change like this is made without flagging it. 

There are down stream non-technical impacts which for some teams might be deemed breaking and for some teams licenses such as Apache 2 might not be acceptable where as MIT is. Similarly if you were to change to the GPL or LGPL in a similar way that could cause much larger issues if not flagged appropriately.

**Comment by jcoglan** [comment]
@eyn as I have requested above, I would like us not to get into hypothetical questions. If you are fine with the license change then I don't see a lot of value in debating this.

**Comment by JB1959** [comment]
I haven't been shown what my job is.  Can you tell me what I am supposed to
do?  Who am I working for or with?

Joan Bivens

**Comment by coreyward** [comment]
@jcoglan You are asking for 3,818,753 repositories to either continue using a version of this code that has a known security vulnerability or update their license notifications as a condition of obtaining a patch. That's unethical. 

You claim that you cannot unpublish a release, and [that is not technically true](https://docs.npmjs.com/cli/unpublish). However, even without rescinding 0.1.4 from publication you can do the right thing by releasing a new patch version reverting the change to an Apache 2.0 license.

Then, if you would like for subsequent work on this project to be licensed under Apache 2.0 you can follow what SemVer community recommends by releasing the project under a new name. Alternately, you can do as has been suggested repeatedly and release a new major version. 

**In no scenario is releasing a breaking change as a patch version in a release containing a critical security fix appropriate.**

**Comment by jcoglan** [comment]
@coreyward As I have indicated above, I am happy to discuss any specific problems users are having in adopting this change. Is your organisation or project unable to adopt the release containing the security patch?

**Comment by coreyward** [comment]
> @coreyward As I have indicated above, I am happy to discuss any specific problems users are having in adopting this change. Is your organisation or project unable to adopt the release containing the security patch?

That's fine that you're happy to discuss as much. Alas, as communication goes, you can only control your response, not the input.

Narrowly defining the terms for considering the viewpoints of other people—even in very reasonable sounding language—in an effort to dismiss the content of their message is the tactic of bullies. Censor as you see fit, but don't kid yourself into believing it appears reasonable to observers.

Your behavior suggests a desire to bait organizations into violation of your intellectual property rights, perhaps to gain leverage or for the purposes of seeking monetary relief. I hope that's not the case, but with your refusal to engage in any constructive dialog it's hard to say. Hopefully some tech-focused publications pick up on this and can make some of the millions of users of this software aware of this liability you've foisted upon them unsuspectingly, whether nefarious or not.

**Comment by MrJacobs9020** [comment]
> License changes are a "breaking change" as far as the usability of packages is concerned for many organizations. The change should be reverted and published to a new version.

What version will be best for me?

**Comment by jcoglan** [comment]
I am going to close this issue -- it's been 8 months since this release went out and nobody has come to me with a concrete problem where this license change caused them not to be able to upgrade this package. If anyone _has_ experienced such a problem, I remain open to discussing it.
